live_config_reload = true
import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "Iosevka Term"
style = "Heavy"

[font.bold_italic]
family = "Iosevka Term"
style = "Heavy Italic"

[font.italic]
family = "Iosevka Term"
style = "Medium Italic"

[font.normal]
family = "Iosevka Term"
style = "Medium"

[window]
dynamic_padding = false

[keyboard]
bindings = [{key ="F11", action = "ToggleFullscreen"}, 
{key= "V", mods = "Control", action= "Paste"},
]

