theme="bogster"

[editor]
mouse = false
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = false
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1
